language: java

script: 
- mvn package -Popenshift
deploy:
  provider: openshift
  user: hivanamaced@gmail.com
  password: passwordgcm
  app: calculadora
  domain: hivanah
  on:
    repo: hivanamcd/calculadora-web-gcm
