language: java
script: mvn package -Popenshift
deploy:
  provider: openshift
  user: hivanamaced@gmail.com
  password:
    secure: C105mt0c09PZPW3U01FVFDvPcytJas30kUm5yvb3cwD9iqjrRMcfYSyK0Pz3q8IIosfSnKeYleBIVotRr8/uon623LS7KC6ACfQ7wje72dWmK09m7ZSBIZx7Jm9XupY4CcLsWCKZQsPqCF6mui52zW4kMFY3f5jzxzv18iGCerQ=
  app: calculadora
  domain: hivanah
  on:
    repo: hivanamcd/calculadora-web-gcm
